Add one-time sync Company Data & Company Search docs
PassFort/integration-docs pull request #7
Opened 2021-01-21 10:23 UTC by jac32

2021-01-21 10:34 UTC, jac32 commented on source/includes/_01-config.html.md
> +The list of possible features varies depending on the check type and often
```suggestion
The list of possible features varies depending on the check type but are often used to
```

2021-01-21 10:34 UTC, jac32 commented on source/includes/_08-additional-features.md.erb
> +        This field contains the known profile information on the company the
```suggestion
        This field contains the known profile information on the company
```

2021-01-21 10:34 UTC, jac32 commented on source/includes/_08-additional-features.md.erb
> +        company check should be run for.
```suggestion
        being searched for.
```

2021-01-25 16:20 UTC, Diggsey requested changes

2021-01-25 16:20 UTC, Diggsey commented on source/includes/_08-additional-features.md.erb
> +## Company Search
We should specify the feature identifier here (ie. `COMPANY_SEARCH`)

2021-01-25 17:44 UTC, andreeagherman commented on source/json/responses/run_check_sync_company_data.json
> +        "sic_codes": [
should we remove `sic_codes` if we have `industry_classifications`?

2021-02-05 13:41 UTC, Diggsey approved these changes

2021-02-05 13:45 UTC, merged

2021-02-05 13:45 UTC, andreeagherman approved these changes